# Site settings
title: Confoog
tagline: YAML Configuration for your Ruby applications.
email: seapagan@gmail.com
description: >
  Confoog Open Source Ruby Gem YAML Configuration
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://confoog.seapagan.net" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: pygments
