# Site settings
title: Confoog
tagline: Use YAML Configuration files in your Ruby applications and Gems.
email: seapagan@gmail.com
description: >
  Confoog Open Source Ruby Gem YAML Configuration
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://confoog.seapagan.net" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: pygments

exclude: [README.md, Gemfile, Gemfile.lock]
